[project]
name = "pyano"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "cffi>=2.0.0",
    "numpy>=2.3.5",
    "pycparser>=2.23",
    "pynput>=1.8.1",
    "six>=1.17.0",
    "sounddevice>=0.5.3",
]
